### ISSUE TITLE
Notes error Bayes exercise?

### ISSUE THREAD

**Issue by gusmonod** [jacobeisenstein/gt-nlp-class#18]
Hi,

I have to say that I am not totally sure, but I think that there is a mistake in the review of basic probability, on the example using Bayes rule (Lana Linguist's pattern matcher).

Page 19, equation (1.23) states that

> Pr(T ∩ ¬G) = Pr(T | G) × Pr(¬G)

instead of

> Pr(T ∩ ¬G) = Pr(T | ¬G) × Pr(¬G)

~Because of this, the numbers are wrong, as Pr(T | ¬G) = .995 and not .005~

EDIT: Pr(T | ¬G) is indeed .005, so the numbers are not wrong.

~The rest of the derivation up to equation (1.28) is wrong because of this error.~

~In order to correct this, we should change the four equations below:~

> ~Pr(T ∩ ¬G) = Pr(T | ¬G) × Pr(¬G) = 0.995 × (1−10^−5) ≈ 0.995 (1.23)~
> ~= 0.95 × 10^−5 + 0.995 ≈ 0.005 (1.25)~
> ~= 0.95 × 10^−5 / (0.95 × 10^−5 + 0.995 × (1−10^−5)) (1.27)~
> ~≈ 0.00001 (1.28)~

~The pattern matcher is even less useful than previously thought!~

**Comment by jacobeisenstein** [comment]
Thanks for the correction. I believe that equation (1.23) should say $\Pr(T \cap \neg G) = \Pr(T \mid \neg G) \times \Pr(\neg G)$, but everything else is correct. The example stipulates that $\Pr(T \mid \neg G) = .005$, this is the definition of the false positive rate.

**Comment by gusmonod** [comment]
Oh yes, I did get False Positive and True Negative mixed up.
