### ISSUE TITLE
Possible typo in Equation 2.58

### ISSUE THREAD

**Issue by ywwbill** [jacobeisenstein/gt-nlp-class#25]
Dear Prof. Eisenstein,

I guess there should be a minus sign at the beginning of the right side of the equation:

l_{LogReg} (\theta; x^{(i)}, y^{(i)}) = - \theta f(x^{(i)}, y^{(i)}) + rest of the equation

This can be also illustrated by Equation 2.60.

Thank you for sharing your book! I enjoy reading it.

Weiwei

**Comment by jacobeisenstein** [comment]
Yep, thanks!
