### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by illy** [jacobeisenstein/gt-nlp-class#26]
Hi Jacob,

The footnote 13 (under line 1057) of the class note (version June 1, 2018): 

> A function f is convex iff αf(x i )+(1−α)f(x j ) ≥ f(αx i +(1−α)x j ),

Should 'iff' be 'if'? Thanks a lot!

Best,

S

**Comment by torayeff** [comment]
@illy "iff" means "if and only if", so I guess this is not typo.
