### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Timovdw** [jacobeisenstein/gt-nlp-class#27]
In the version 'draft 3 june' at line 1892 there is word duplication by accident:

> Classification of these **relations relations** can be performed by searching for characteristic patterns between pairs of words

The word *relations* appears twice.

By the way, so far, great read, thx a lot for opensourcing this!

**Comment by jacobeisenstein** [comment]
Thanks! Will close it in a moment. I'll add an acknowledgment to the preface if you send your full name.

**Comment by Timovdw** [comment]
No need to thank me, you did all the work.
