### ISSUE TITLE
Possible missing subscript on Equation for CRFs

### ISSUE THREAD

**Issue by lzfelix** [jacobeisenstein/gt-nlp-class#29]
Dear professor Eisenstein,

Thank you very much for making the book publicly available.
I would like to point a possible typo on the equation on section 7.5.3.1:

![](https://image.ibb.co/crrXKd/Screen_Shot_2018_06_19_at_9_52_12_am.png)

Should not the `s` function be written `s_m`, indicating the transition between labels `y_{m-1}` and `y_m` on the `i`-th position of the underlying `w` sequence?

Thank you very much,
Luiz C F Ribeiro

**Comment by yuvalpinter** [comment]
Hi Luiz,
IIRC `s` is a global transition matrix, which is not dependent on position.
- Yuval

**Comment by lzfelix** [comment]
Hi Yuval,

You are right regarding the transition matrix being global, irrespective to elements position.

I actually forgot the complete definition of `s_m(y_m, y_{m-1})` from an example on the book, where the function is defined as a sum of the score of the `m`-th element of the sequence having the label `y` and the transition between tags. This is defined formally on Equation 7.16.

What caught my attention is that `s` has always a subscript on this chapter, except on this equation.

**Comment by jacobeisenstein** [comment]
Luis, you are correct. s_m is indexed by m because it describes the score
for the tag transition y_{m-1} -> y_m specifically on position m. I will
make an update. Thanks!
-Jacob
