### ISSUE TITLE
Bibtex entry

### ISSUE THREAD

**Issue by lzfelix** [jacobeisenstein/gt-nlp-class#33]
Dear professor,

Once again thank you very much for making this material publicly available. Is there any default Bibtex that we should use to cite the notes?

Thank you.

**Comment by jacobeisenstein** [comment]
Sorry for the delay! The book is forthcoming with MIT Press, hopefully in 2019. You could use that information to make a bibtex entry for now, if you still need one.

**Comment by lzfelix** [comment]
Great! I am citing in in my Masters Dissertation :)
