### ISSUE TITLE
question

### ISSUE THREAD

**Issue by raynerr** [jacobeisenstein/gt-nlp-class#36]
Hi, thank you for your great book.
I am confused about the subscript in formula 3.29, which I think the zk should be zj (sorry for the uncorrect typing shape). 
Thanks.

**Comment by jacobeisenstein** [comment]
I'm glad you're enjoying the book!

I could be missing something, but I think it is correct. The parameter
$\theta_{k,j}$ is the weight from $z_k$ to $y = j$. Thus, the gradient
depends on $z_k$, not $z_j$.

**Comment by raynerr** [comment]
Thank you for your reply.
In my opinion, according to the previous context, column k should represent y = k and j might represent the element in $z_k$ as illustrated in the picture I uploaded.
Or, if $ j $ represents $y =j$ and $ k $ should represent the element in $z_j$, which means that the text " $theta_k(z-->y)$ is column $ k $ of ..." in left notation [1487] may be not reasonable.
Sorry to disturb you again.


![illustration](https://user-images.githubusercontent.com/37948688/43813644-2442686c-9af9-11e8-8b9a-4e793bd5fc0d.jpg)

**Comment by jacobeisenstein** [comment]
Sorry, I still don't see it. The size of the matrix \Theta^{(zy)} is K_y
rows and K_z columns, as required by the matrix-vector product
\Theta^{(zy)} z. One thing that may be adding confusion is that k indexes
an input feature in theta^{(xz)} [3.26], and a hidden layer element in
\theta^{(zy)} [3.25]. I've changed the notation to be more consistent on
this point: n indexes input features, k indexes elements in the hidden
layer, and j indexes labels.

**Comment by raynerr** [comment]
Oh, I got it.
So sorry about my mistake.
Thanks a lot, Mr Eisenstein.

**Comment by jacobeisenstein** [comment]
No problem! -J
