### ISSUE TITLE
Possible error on 4.4.1

### ISSUE THREAD

**Issue by jiahao42** [jacobeisenstein/gt-nlp-class#39]
Hi there,

I think the selected sentence should be `A high-recall classifier is preferred when false positives are cheaper than false negatives`.

![image](https://user-images.githubusercontent.com/12411648/44995090-873db900-af6f-11e8-915e-7a869a111f09.png)

Thanks.

**Comment by jacobeisenstein** [comment]
You're right, thanks! -J
