### ISSUE TITLE
Any plan to publish the book?

### ISSUE THREAD

**Issue by dyngts** [jacobeisenstein/gt-nlp-class#41]
Dear @jacobeisenstein,

First of all, really appreciate for write book of NLP with recent trends. I know this is too early, but any raw plan to make this "book" become actual book? Sorry if i'm missing your statement about this.

Besides, i'm willing to read your book but seems the content not final yet. Could you give some notes which chapters or sections that might still in early stage/prone to error? is it what you mark it with "*" sign in the TOC? Thank you, can't wait for the final version.

**Comment by jacobeisenstein** [comment]
Hi thanks for your interest in the book. It is under contract with MIT
press. I'm happy to get edits for any chapter for another few weeks. I've
gotten many more edits on the first few chapters, so I'd be especially glad
to get feedback on the later chapters.

**Comment by dyngts** [comment]
Awesome then @jacobeisenstein, can't wait for the book get published!
