### ISSUE TITLE
Suggestion for the commit message

### ISSUE THREAD

**Issue by dyngts** [jacobeisenstein/gt-nlp-class#42]
Dear @jacobeisenstein,

Thanks to always improve content quality of your NLP note. However, i found difficulty to refer the actual changes since your commit message too brief without any details. This also due to the nature of PDF file which harder to track the diff.

If you mind, i recommend to add more details about the changes in commit message, at least the location of the diff (e.g: which page and section). Thus, instead redownload your note, i can just correct it manually by my hand.

Hope this not overwhelming, thanks

**Comment by jacobeisenstein** [comment]
Yeah the commit messages are really just for my own benefit, I understand that a detailed changelog would be helpful for readers, but I don't have time. I'm about to submit the next version to the publisher, so the pace of edits will probably slow down for a while.
